import type { ExtractSchema, TraitValue } from 'koota';
import type { Requirement } from './actions.js';
import type { Screen, ScreenTransition } from './traits.js';
import { packages } from '../package/data.js';
import { currentTeam, profiles } from '../profile/data.js';

export type ScreenDefinition = TraitValue<ExtractSchema<typeof Screen>> & {
  id: string;
  requires: readonly Requirement[];
  transition: TraitValue<ExtractSchema<typeof ScreenTransition>>;
};

// The maintainers who gather around Paul first, followed by the wider contributor group.
const founding = [
  'gsimone',
  'CodyJasonBennett',
  'dai-shi',
  'dbismut',
  'stephencorwin',
  'joshuaellis',
];
const following = profiles
  .map((profile) => profile.login)
  .filter(
    (login) =>
      !['drcmda', 'kvvasuu', 'thejustinwalsh', 'DennisSmolek', 'castavridis'].includes(login) &&
      !founding.includes(login)
  );

// Screens are visited in list order, with transition durations in seconds.
// cameraDelay holds the camera at its origin for that many seconds before it moves, and
// revealDelay holds views that opt into delayed reveals for that many seconds.
export const screens = [
  {
    id: 'title',
    requires: ['camera', 'title'],
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'warp-launch',
    requires: ['camera', 'title'],
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'intro',
    requires: ['camera', 'title', 'packages'],
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageStagger: 0.12,
    packageDownloadsVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.15, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'code-comparison',
    requires: ['camera', 'title'],
    titleVisible: true,
    codeComparisonVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.6, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'three-features',
    requires: ['camera', 'title', 'packages'],
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageEntry: 'rise',
    packageDelay: 0.35,
    packageDuration: 1.05,
    packageFeaturesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'robot',
    requires: ['camera', 'title', 'packages'],
    titleVisible: true,
    robotVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageFeaturesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 3.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'warp-through',
    requires: ['camera', 'title'],
    titleVisible: true,
    warpVisible: true,
    autoAdvance: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    transition: { duration: 2.8, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'packages',
    requires: ['camera', 'letters', 'packages'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageDelay: 0.7,
    packageDuration: 0.95,
    packageStagger: 0.025,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.1, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'package-maintainers',
    requires: ['camera', 'letters', 'packages'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageMaintainersVisible: true,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'package-sizes',
    requires: ['camera', 'letters', 'packages'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageDuration: 0.95,
    packageStagger: 0.025,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'letters',
    requires: ['camera', 'letters'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.9, cameraX: 0, cameraY: 0, cameraZ: 8 },
  },
  {
    id: 'profiles',
    requires: ['camera', 'letters', 'profiles'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'hello',
    requires: ['camera', 'letters', 'profiles'],
    greetingVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.3, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'history-logos',
    requires: ['camera', 'letters', 'profiles'],
    historyPages: 1,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.1, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'history-name',
    requires: ['camera', 'letters', 'profiles'],
    historyPages: 2,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.1, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'history-reserved',
    requires: ['camera', 'letters', 'profiles'],
    historyPages: 3,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.1, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'work',
    requires: ['camera', 'letters', 'profiles'],
    greetingVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.4, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'paul-community',
    requires: ['camera', 'letters', 'profiles'],
    // Paul steps out of the middle and the group gathers with him into a ring
    surroundingProfiles: ['drcmda', ...founding],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'community-reel',
    requires: ['camera', 'letters', 'profiles'],
    surroundingProfiles: ['drcmda', ...founding],
    // The portal clip opens behind the portraits, then pulls back to the whole wall
    showreelVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'community-next',
    requires: ['camera', 'letters', 'profiles'],
    showreelVisible: true,
    // Close the wall in on the bottom right tile, then cut to the next clip
    showreelFocus: 15,
    recedingProfiles: ['drcmda', ...founding],
    surroundingProfiles: following,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    // The portraits set off as the wall's close in starts to settle, overlapping its tail,
    // and finish on the held tile. The reel cuts once this transition is done.
    transition: { duration: 3.8, revealDelay: 1.6, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'community-growth',
    requires: ['camera', 'letters', 'packages', 'profiles'],
    communityDeparture: true,
    showreelVisible: true,
    showreelFocus: 15,
    recedingProfiles: ['drcmda', ...founding],
    surroundingProfiles: following,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: ['@react-three/fiber'],
    packageLayout: 'community',
    packageDownloadsVisible: true,
    packageDelay: 0.05,
    packageDuration: 0.65,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 3.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'community-robot',
    requires: ['camera', 'letters', 'packages', 'profiles'],
    communityDeparture: true,
    communityRobotVisible: true,
    showreelVisible: true,
    showreelFocus: 15,
    recedingProfiles: ['drcmda', ...founding],
    surroundingProfiles: following,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: ['@react-three/fiber'],
    packageLayout: 'community',
    packageDownloadsVisible: true,
    packageDelay: 0.05,
    packageDuration: 0.65,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 3.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'maintainers',
    requires: ['camera', 'letters', 'profiles'],
    teamVisible: true,
    communityRobotVisible: true,
    showreelVisible: true,
    showreelFocus: 15,
    focusedProfile: 'DennisSmolek',
    surroundingProfiles: ['DennisSmolek', 'krispya'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 4.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'maintainer-team',
    requires: ['camera', 'letters', 'profiles'],
    teamVisible: true,
    robotFriendly: true,
    robotJoinDelay: 4.3,
    communityRobotVisible: true,
    focusedProfile: 'DennisSmolek',
    surroundingProfiles: currentTeam,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 6.7, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'principles',
    requires: ['camera', 'letters', 'profiles'],
    principlesVisible: true,
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    focusedProfile: 'DennisSmolek',
    surroundingProfiles: currentTeam,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    // The curtain lands before the four principles enter over it
    transition: { duration: 3.6, revealDelay: 1.75, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'principles-tasteful',
    requires: ['camera', 'letters', 'profiles'],
    principlesVisible: true,
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    focusedProfile: 'DennisSmolek',
    surroundingProfiles: currentTeam,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    // Lift the existing list before the fifth principle arrives
    transition: { duration: 2.2, revealDelay: 0.65, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'principles-logo',
    requires: ['camera', 'letters', 'profiles'],
    principlesVisible: true,
    principlesLogo: true,
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    focusedProfile: 'DennisSmolek',
    surroundingProfiles: currentTeam,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    // The words lift into pieces that glide together as the mark
    transition: { duration: 2.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter',
    requires: ['camera', 'letters', 'profiles', 'charter'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    charterVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 3.6, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter-initiatives',
    requires: ['camera', 'letters', 'profiles', 'charter'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    charterVisible: true,
    charterHighlight: 'initiatives',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter-initiatives-focus',
    requires: ['camera', 'letters', 'profiles', 'charter'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    charterVisible: true,
    charterHighlight: 'initiatives',
    charterFocus: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.2, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'initiative-story',
    requires: ['camera', 'letters', 'profiles', 'charter'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    storyProfile: 'krispya',
    charterVisible: true,
    charterHighlight: 'initiatives',
    charterFocus: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'initiative-connections',
    requires: ['camera', 'letters', 'profiles', 'charter'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    storyProfile: 'krispya',
    storyConnectionsVisible: true,
    charterVisible: true,
    charterHighlight: 'initiatives',
    charterFocus: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter-announcement',
    requires: ['camera', 'letters', 'profiles'],
    teamVisible: true,
    robotFriendly: true,
    communityRobotVisible: true,
    surroundingProfiles: currentTeam,
    storyProfile: 'krispya',
    charterFocus: true,
    announcementVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.8, revealDelay: 0.65, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'constellation',
    requires: ['camera', 'letters', 'profiles'],
    autoAdvance: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    profilesVisible: true,
    backgroundVisible: true,
    transition: {
      duration: 4.6,
      cameraDelay: 2.1,
      revealDelay: 2.35,
      cameraX: 0,
      cameraY: 0,
      cameraZ: 120,
    },
  },
  {
    id: 'portal-fall',
    requires: ['camera', 'letters', 'profiles', 'initiatives'],
    initiativePortalVisible: true,
    initiative: 'r3f-v10',
    autoAdvance: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    profilesVisible: true,
    backgroundVisible: true,
    transition: {
      duration: 5.2,
      cameraDelay: 2.6,
      cameraEase: 'portalFall',
      cameraX: 0,
      cameraY: 0,
      cameraZ: -18,
    },
  },
  {
    id: 'initiatives',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'r3f-v10',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-r3f-features',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'r3f-v10',
    initiativeChips: ['Declarative WebGPU', 'New scheduler', 'TSL hooks', 'Drei reborn'],
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-glyph',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'glyph',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-design-system',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'design-system',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-math',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'math',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'math-benchmark',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'math',
    benchmarkVisible: true,
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'math-three-benchmark',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'math',
    benchmarkVisible: true,
    benchmarkVariant: 'three',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-experimental',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'experimental',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-games',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'games',
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'initiative-games-features',
    requires: ['camera', 'initiatives'],
    initiativesVisible: true,
    initiative: 'games',
    initiativeChips: ['crashcat', 'navcat', 'gpucat', 'more!'],
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'closing',
    requires: ['camera'],
    closingVisible: true,
    background: 'blue',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.4, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
] as const satisfies readonly ScreenDefinition[];

export type ScreenId = (typeof screens)[number]['id'];
