// Screens are visited in list order, with transition durations in seconds.
// cameraDelay holds the camera at its origin for that many seconds before it moves, and
// revealDelay holds views that opt into delayed reveals for that many seconds.
export const screens = [
  {
    id: 'title',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'intro',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['react-three-fiber', 'three'],
    packageLayout: 'pair',
    packageStagger: 0.12,
    packageDelay: 2.7,
    packageDownloadsVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 3.85, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'code-comparison',
    titleVisible: true,
    codeComparisonVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.6, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'three-features',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['react-three-fiber', 'three'],
    packageLayout: 'pair',
    packageEntry: 'rise',
    packageDelay: 0.35,
    packageDuration: 1.05,
    packageFeaturesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'package-sizes',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'letters',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.9, cameraX: 0, cameraY: 0, cameraZ: 8 },
  },
  {
    id: 'profiles',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'constellation',
    initiativesVisible: true,
    constellation: 'principles',
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.8, cameraX: 0, cameraY: 0, cameraZ: 120 },
  },
  {
    id: 'principles',
    constellation: 'principles',
    constellationMap: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 4, cameraX: 106, cameraY: 8, cameraZ: -20 },
  },
  {
    id: 'charter',
    constellation: 'principles',
    constellationMap: true,
    charterVisible: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 3.6, cameraX: 106, cameraY: 8, cameraZ: -20 },
  },
  {
    id: 'charter-initiatives',
    constellation: 'principles',
    constellationMap: true,
    charterVisible: true,
    charterHighlight: 'initiatives',
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 106, cameraY: 8, cameraZ: -20 },
  },
  {
    id: 'initiatives',
    initiativesVisible: true,
    constellation: 'principles',
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: {
      duration: 4.6,
      cameraDelay: 2.1,
      revealDelay: 3.1,
      cameraX: 0,
      cameraY: 0,
      cameraZ: 120,
    },
  },
] as const;

export type ScreenId = (typeof screens)[number]['id'];
