import { packages } from '../data/packages.js';

// Screens are visited in list order, with transition durations in seconds.
// cameraDelay holds the camera at its origin for that many seconds before it moves, and
// revealDelay holds views that opt into delayed reveals for that many seconds.
export const screens = [
  {
    id: 'title',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'warp-launch',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'intro',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageStagger: 0.12,
    packageDownloadsVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.15, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'code-comparison',
    titleVisible: true,
    codeComparisonVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.6, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'three-features',
    titleVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageEntry: 'rise',
    packageDelay: 0.35,
    packageDuration: 1.05,
    packageFeaturesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'robot',
    titleVisible: true,
    robotVisible: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: true,
    packageNames: ['@react-three/fiber', 'three'],
    packageLayout: 'pair',
    packageFeaturesVisible: true,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 3.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'warp-through',
    titleVisible: true,
    warpVisible: true,
    autoAdvance: true,
    background: 'solid',
    lettersVisible: false,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    transition: { duration: 2.8, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'packages',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageDelay: 0.7,
    packageDuration: 0.95,
    packageStagger: 0.025,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 2.1, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'package-maintainers',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageMaintainersVisible: true,
    packageSizing: 'compressed',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'package-sizes',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: true,
    packageNames: packages.filter((pkg) => pkg.name !== 'three').map((pkg) => pkg.name),
    packageDuration: 0.95,
    packageStagger: 0.025,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 1.4, cameraX: 0, cameraY: 0, cameraZ: 12 },
  },
  {
    id: 'letters',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.9, cameraX: 0, cameraY: 0, cameraZ: 8 },
  },
  {
    id: 'profiles',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.8, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'hello',
    greetingVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.3, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'paul',
    focusedProfile: 'drcmda',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2.6, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'paul-community',
    focusedProfile: 'drcmda',
    surroundingProfiles: ['dai-shi', 'CodyJasonBennett', 'krispya', 'dbismut', 'gsimone'],
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 2, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter',
    charterVisible: true,
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 3.6, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'charter-initiatives',
    charterVisible: true,
    charterHighlight: 'initiatives',
    background: 'pastel',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 1.2, cameraX: 0, cameraY: 0, cameraZ: -5 },
  },
  {
    id: 'constellation',
    autoAdvance: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    profilesVisible: true,
    backgroundVisible: true,
    transition: {
      duration: 4.6,
      cameraDelay: 2.1,
      revealDelay: 2.35,
      cameraX: 0,
      cameraY: 0,
      cameraZ: 120,
    },
  },
  {
    id: 'portal-fall',
    initiativePortalVisible: true,
    autoAdvance: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    profilesVisible: true,
    backgroundVisible: true,
    transition: {
      duration: 5.2,
      cameraDelay: 2.6,
      cameraEase: 'portalFall',
      cameraX: 0,
      cameraY: 0,
      cameraZ: -18,
    },
  },
  {
    id: 'initiatives',
    initiativesVisible: true,
    background: 'stars',
    lettersVisible: false,
    packagesVisible: false,
    profilesVisible: false,
    backgroundVisible: true,
    transition: { duration: 0.8, cameraX: 0, cameraY: 0, cameraZ: -18 },
  },
  {
    id: 'principles',
    constellation: 'principles',
    constellationMap: true,
    background: 'stars',
    lettersVisible: true,
    packagesVisible: false,
    packageSizing: 'proportional',
    profilesVisible: true,
    backgroundVisible: true,
    transition: { duration: 4, cameraX: 106, cameraY: 8, cameraZ: -20 },
  },
] as const;

export type ScreenId = (typeof screens)[number]['id'];
